# Creating DataFrame

### using lists

In [1]:
import numpy as np
import pandas as pd

In [2]:
a = pd.DataFrame([1,2,3,4])

In [3]:
type(a)

pandas.core.frame.DataFrame

Using a 2D list

In [4]:
student_data = [
    [100,80,10],
    [90,70,7],
    [120,100,14],
    [80,50,2]
]

creating the dataframe

In [5]:
pd.DataFrame(student_data,columns=['iq','marks','package'])

iq  marks  package
0  100     80       10
1   90     70        7
2  120    100       14
3   80     50        2

### using dicts

In [6]:
student_dict = {
    'iq':[100,90,120,80,0,0],
    'marks':[80,70,100,50,0,0],
    'package':[10,7,14,2,0,0]
}

creating the dataframe

In [7]:
pd.DataFrame(student_dict)

iq  marks  package
0  100     80       10
1   90     70        7
2  120    100       14
3   80     50        2
4    0      0        0
5    0      0        0

Storing in into a variable

In [8]:
students = pd.DataFrame(student_dict)
students

iq  marks  package
0  100     80       10
1   90     70        7
2  120    100       14
3   80     50        2
4    0      0        0
5    0      0        0

### using read_csv

In [9]:
pd.read_csv('movies.csv')
movies = pd.read_csv('movies.csv')
movies

title_x     imdb_id  \
0                 Uri: The Surgical Strike   tt8291224   
1                            Battalion 609   tt9472208   
2     The Accidental Prime Minister (film)   tt6986710   
3                          Why Cheat India   tt8108208   
4                          Evening Shadows   tt6028796   
...                                    ...         ...   
1624                 Tera Mera Saath Rahen   tt0301250   
1625                  Yeh Zindagi Ka Safar   tt0298607   
1626                       Sabse Bada Sukh   tt0069204   
1627                                 Daaka  tt10833860   
1628                              Humsafar   tt2403201   

                                            poster_path  \
0     https://upload.wikimedia.org/wikipedia/en/thum...   
1                                                   NaN   
2     https://upload.wikimedia.org/wikipedia/en/thum...   
3     https://upload.wikimedia.org/wikipedia/en/thum...   
4                                                   NaN   
...                                                 ...   
1624  https://upload.wikimedia.org/wikipedia/en/2/2b...   
1625  https://upload.wikimedia.org/wikipedia/en/thum...   
1626                                                NaN   
1627  https://upload.wikimedia.org/wikipedia/en/thum...   
1628  https://upload.wikimedia.org/wikipedia/en/thum...   

                                              wiki_link  \
0     https://en.wikipedia.org/wiki/Uri:_The_Surgica...   
1           https://en.wikipedia.org/wiki/Battalion_609   
2     https://en.wikipedia.org/wiki/The_Accidental_P...   
3         https://en.wikipedia.org/wiki/Why_Cheat_India   
4         https://en.wikipedia.org/wiki/Evening_Shadows   
...                                                 ...   
1624  https://en.wikipedia.org/wiki/Tera_Mera_Saath_...   
1625  https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...   
1626      https://en.wikipedia.org/wiki/Sabse_Bada_Sukh   
1627                https://en.wikipedia.org/wiki/Daaka   
1628             https://en.wikipedia.org/wiki/Humsafar   

                            title_y                 original_title  is_adult  \
0          Uri: The Surgical Strike       Uri: The Surgical Strike         0   
1                     Battalion 609                  Battalion 609         0   
2     The Accidental Prime Minister  The Accidental Prime Minister         0   
3                   Why Cheat India                Why Cheat India         0   
4                   Evening Shadows                Evening Shadows         0   
...                             ...                            ...       ...   
1624          Tera Mera Saath Rahen          Tera Mera Saath Rahen         0   
1625           Yeh Zindagi Ka Safar           Yeh Zindagi Ka Safar         0   
1626                Sabse Bada Sukh                Sabse Bada Sukh         0   
1627                          Daaka                          Daaka         0   
1628                       Humsafar                       Humsafar         0   

      year_of_release runtime            genres  imdb_rating  imdb_votes  \
0                2019     138  Action|Drama|War          8.4       35112   
1                2019     131               War          4.1          73   
2                2019     112   Biography|Drama          6.1        5549   
3                2019     121       Crime|Drama          6.0        1891   
4                2018     102             Drama          7.3         280   
...               ...     ...               ...          ...         ...   
1624             2001     148             Drama          4.9         278   
1625             2001     146             Drama          3.0         133   
1626             2018      \N      Comedy|Drama          6.1          13   
1627             2019     136            Action          7.4          38   
1628             2011      35     Drama|Romance          9.0        2968   

                                              

Loading the other dataset

In [10]:
ipl = pd.read_csv('ipl-matches.csv')
ipl

ID        City        Date   Season  MatchNumber  \
0    1312200   Ahmedabad  2022-05-29     2022        Final   
1    1312199   Ahmedabad  2022-05-27     2022  Qualifier 2   
2    1312198     Kolkata  2022-05-25     2022   Eliminator   
3    1312197     Kolkata  2022-05-24     2022  Qualifier 1   
4    1304116      Mumbai  2022-05-22     2022           70   
..       ...         ...         ...      ...          ...   
945   335986     Kolkata  2008-04-20  2007/08            4   
946   335985      Mumbai  2008-04-20  2007/08            5   
947   335984       Delhi  2008-04-19  2007/08            3   
948   335983  Chandigarh  2008-04-19  2007/08            2   
949   335982   Bangalore  2008-04-18  2007/08            1   

                           Team1                        Team2  \
0               Rajasthan Royals               Gujarat Titans   
1    Royal Challengers Bangalore             Rajasthan Royals   
2    Royal Challengers Bangalore         Lucknow Super Giants   
3               Rajasthan Royals               Gujarat Titans   
4            Sunrisers Hyderabad                 Punjab Kings   
..                           ...                          ...   
945        Kolkata Knight Riders              Deccan Chargers   
946               Mumbai Indians  Royal Challengers Bangalore   
947             Delhi Daredevils             Rajasthan Royals   
948              Kings XI Punjab          Chennai Super Kings   
949  Royal Challengers Bangalore        Kolkata Knight Riders   

                                          Venue                   TossWinner  \
0              Narendra Modi Stadium, Ahmedabad             Rajasthan Royals   
1              Narendra Modi Stadium, Ahmedabad             Rajasthan Royals   
2                         Eden Gardens, Kolkata         Lucknow Super Giants   
3                         Eden Gardens, Kolkata               Gujarat Titans   
4                      Wankhede Stadium, Mumbai          Sunrisers Hyderabad   
..                                          ...                          ...   
945                                Eden Gardens              Deccan Chargers   
946                            Wankhede Stadium               Mumbai Indians   
947                            Feroz Shah Kotla             Rajasthan Royals   
948  Punjab Cricket Association Stadium, Mohali          Chennai Super Kings   
949                       M Chinnaswamy Stadium  Royal Challengers Bangalore   

    TossDecision SuperOver                  WinningTeam    WonBy  Margin  \
0            bat         N               Gujarat Titans  Wickets     7.0   
1          field         N             Rajasthan Royals  Wickets     7.0   
2          field         N  Royal Challengers Bangalore     Runs    14.0   
3          field         N               Gujarat Titans  Wickets     7.0   
4            bat         N                 Punjab Kings  Wickets     5.0   
..           ...       ...                          ...      ...     ...   
945          bat         N        Kolkata Knight Riders  Wickets     5.0   
946          bat         N  Royal Challengers Bangalore  Wickets     5.0   
947          bat         N             Delhi Daredevils  Wickets     9.0   
948          bat         N          Chennai Super Kings     Runs    33.0   
949        field         N        Kolkata Knight Riders     Runs   140.0   

    method Player_of_Match                                       Team1Players  \
0      NaN       HH Pandya  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...   
1      NaN      JC Buttler  ['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...   
2      NaN      RM Patidar  ['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...   
3      NaN       DA Miller  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...   
4      NaN   Harpreet Brar  ['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...   
..     ...             ...                                                ...   
945    NaN       DJ Hussey  ['WP Saha', 'BB

# DataFrame Attributes and Methods

### shape to check how many rows and columns

Usually first thing to check

In [11]:
movies.shape

(1629, 18)

### dtypes

To find out the data types of columns

In [12]:
movies.dtypes

title_x              object
imdb_id              object
poster_path          object
wiki_link            object
title_y              object
original_title       object
is_adult              int64
year_of_release       int64
runtime              object
genres               object
imdb_rating         float64
imdb_votes            int64
story                object
summary              object
tagline              object
actors               object
wins_nominations     object
release_date         object
dtype: object

### index

To fletch the range index object

In [13]:
ipl.index

RangeIndex(start=0, stop=950, step=1)

In [14]:
movies.index

RangeIndex(start=0, stop=1629, step=1)

### columns

To fletch all the columns, returns an index object

In [15]:
movies.columns

Index(['title_x', 'imdb_id', 'poster_path', 'wiki_link', 'title_y',
       'original_title', 'is_adult', 'year_of_release', 'runtime', 'genres',
       'imdb_rating', 'imdb_votes', 'story', 'summary', 'tagline', 'actors',
       'wins_nominations', 'release_date'],
      dtype='object')

### values

To get all the values, returns a 2D numpy array of values

In [16]:
ipl.values

array([[1312200, 'Ahmedabad', '2022-05-29', ...,
        "['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pandya', 'DA Miller', 'R Tewatia', 'Rashid Khan', 'R Sai Kishore', 'LH Ferguson', 'Yash Dayal', 'Mohammed Shami']",
        'CB Gaffaney', 'Nitin Menon'],
       [1312199, 'Ahmedabad', '2022-05-27', ...,
        "['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D Padikkal', 'SO Hetmyer', 'R Parag', 'R Ashwin', 'TA Boult', 'YS Chahal', 'M Prasidh Krishna', 'OC McCoy']",
        'CB Gaffaney', 'Nitin Menon'],
       [1312198, 'Kolkata', '2022-05-25', ...,
        "['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda', 'MP Stoinis', 'E Lewis', 'KH Pandya', 'PVD Chameera', 'Mohsin Khan', 'Avesh Khan', 'Ravi Bishnoi']",
        'J Madanagopal', 'MA Gough'],
       ...,
       [335984, 'Delhi', '2008-04-19', ...,
        "['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif', 'DS Lehmann', 'RA Jadeja', 'M Rawat', 'D Salunkhe', 'SK Warne', 'SK Trivedi', 'MM Patel']",
        'Aleem Dar', 'GA Pratapkumar'],
    

### head() and tail() works similarly

In [17]:
movies.head()

title_x    imdb_id  \
0              Uri: The Surgical Strike  tt8291224   
1                         Battalion 609  tt9472208   
2  The Accidental Prime Minister (film)  tt6986710   
3                       Why Cheat India  tt8108208   
4                       Evening Shadows  tt6028796   

                                         poster_path  \
0  https://upload.wikimedia.org/wikipedia/en/thum...   
1                                                NaN   
2  https://upload.wikimedia.org/wikipedia/en/thum...   
3  https://upload.wikimedia.org/wikipedia/en/thum...   
4                                                NaN   

                                           wiki_link  \
0  https://en.wikipedia.org/wiki/Uri:_The_Surgica...   
1        https://en.wikipedia.org/wiki/Battalion_609   
2  https://en.wikipedia.org/wiki/The_Accidental_P...   
3      https://en.wikipedia.org/wiki/Why_Cheat_India   
4      https://en.wikipedia.org/wiki/Evening_Shadows   

                         title_y                 original_title  is_adult  \
0       Uri: The Surgical Strike       Uri: The Surgical Strike         0   
1                  Battalion 609                  Battalion 609         0   
2  The Accidental Prime Minister  The Accidental Prime Minister         0   
3                Why Cheat India                Why Cheat India         0   
4                Evening Shadows                Evening Shadows         0   

   year_of_release runtime            genres  imdb_rating  imdb_votes  \
0             2019     138  Action|Drama|War          8.4       35112   
1             2019     131               War          4.1          73   
2             2019     112   Biography|Drama          6.1        5549   
3             2019     121       Crime|Drama          6.0        1891   
4             2018     102             Drama          7.3         280   

                                               story  \
0  Divided over five chapters  the film chronicle...   
1  The story revolves around a cricket match betw...   
2  Based on the memoir by Indian policy analyst S...   
3  The movie focuses on existing malpractices in ...   
4  While gay rights and marriage equality has bee...   

                                             summary tagline  \
0  Indian army special forces execute a covert op...     NaN   
1  The story of Battalion 609 revolves around a c...     NaN   
2  Explores Manmohan Singh's tenure as the Prime ...     NaN   
3  The movie focuses on existing malpractices in ...     NaN   
4  Under the 'Evening Shadows'  truth often plays...     NaN   

                                              actors        wins_nominations  \
0  Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...                  4 wins   
1  Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...                     NaN   
2  Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...                     NaN   
3  Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...                     NaN   
4  Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...  17 wins & 1 nomination   

              release_date  
0    11 January 2019 (USA)  
1  11 January 2019 (India)  
2    11 January 2019 (USA)  
3    18 January 2019 (USA)  
4  11 January 2019 (India)

In [18]:
ipl.tail(6)

ID        City        Date   Season MatchNumber  \
944  335987      Jaipur  2008-04-21  2007/08           6   
945  335986     Kolkata  2008-04-20  2007/08           4   
946  335985      Mumbai  2008-04-20  2007/08           5   
947  335984       Delhi  2008-04-19  2007/08           3   
948  335983  Chandigarh  2008-04-19  2007/08           2   
949  335982   Bangalore  2008-04-18  2007/08           1   

                           Team1                        Team2  \
944             Rajasthan Royals              Kings XI Punjab   
945        Kolkata Knight Riders              Deccan Chargers   
946               Mumbai Indians  Royal Challengers Bangalore   
947             Delhi Daredevils             Rajasthan Royals   
948              Kings XI Punjab          Chennai Super Kings   
949  Royal Challengers Bangalore        Kolkata Knight Riders   

                                          Venue                   TossWinner  \
944                      Sawai Mansingh Stadium              Kings XI Punjab   
945                                Eden Gardens              Deccan Chargers   
946                            Wankhede Stadium               Mumbai Indians   
947                            Feroz Shah Kotla             Rajasthan Royals   
948  Punjab Cricket Association Stadium, Mohali          Chennai Super Kings   
949                       M Chinnaswamy Stadium  Royal Challengers Bangalore   

    TossDecision SuperOver                  WinningTeam    WonBy  Margin  \
944          bat         N             Rajasthan Royals  Wickets     6.0   
945          bat         N        Kolkata Knight Riders  Wickets     5.0   
946          bat         N  Royal Challengers Bangalore  Wickets     5.0   
947          bat         N             Delhi Daredevils  Wickets     9.0   
948          bat         N          Chennai Super Kings     Runs    33.0   
949        field         N        Kolkata Knight Riders     Runs   140.0   

    method Player_of_Match                                       Team1Players  \
944    NaN       SR Watson  ['M Kaif', 'Kamran Akmal', 'YK Pathan', 'SR Wa...   
945    NaN       DJ Hussey  ['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...   
946    NaN      MV Boucher  ['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...   
947    NaN     MF Maharoof  ['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...   
948    NaN      MEK Hussey  ['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...   
949    NaN     BB McCullum  ['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...   

                                          Team2Players    Umpire1  \
944  ['K Goel', 'JR Hopes', 'KC Sangakkara', 'DPMD ...  Aleem Dar   
945  ['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...  BF Bowden   
946  ['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...   SJ Davis   
947  ['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...  Aleem Dar   
948  ['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...  MR Benson   
949  ['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...  Asad Rauf   

            Umpire2  
944       RB Tiffin  
945     K Hariharan  
946       DJ Harper  
947  GA Pratapkumar  
948      SL Shastri  
949     RE Koertzen

### sample()

To see one random row. Helpfull when there's bias in the data. Also it takes an argument sample(x) to see x number of rows, this observation is done to confirm if the data is bias.

In [19]:
ipl.sample()

ID    City        Date Season MatchNumber           Team1  \
127  1254064  Mumbai  2021-04-15   2021           7  Delhi Capitals   

                Team2                     Venue        TossWinner  \
127  Rajasthan Royals  Wankhede Stadium, Mumbai  Rajasthan Royals   

    TossDecision SuperOver       WinningTeam    WonBy  Margin method  \
127        field         N  Rajasthan Royals  Wickets     3.0    NaN   

    Player_of_Match                                       Team1Players  \
127      JD Unadkat  ['PP Shaw', 'S Dhawan', 'AM Rahane', 'RR Pant'...   

                                          Team2Players Umpire1    Umpire2  
127  ['JC Buttler', 'M Vohra', 'SV Samson', 'S Dube...  S Ravi  VK Sharma

### info()

To get high-level information about the data

In [20]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1629 entries, 0 to 1628
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   title_x           1629 non-null   object 
 1   imdb_id           1629 non-null   object 
 2   poster_path       1526 non-null   object 
 3   wiki_link         1629 non-null   object 
 4   title_y           1629 non-null   object 
 5   original_title    1629 non-null   object 
 6   is_adult          1629 non-null   int64  
 7   year_of_release   1629 non-null   int64  
 8   runtime           1629 non-null   object 
 9   genres            1629 non-null   object 
 10  imdb_rating       1629 non-null   float64
 11  imdb_votes        1629 non-null   int64  
 12  story             1609 non-null   object 
 13  summary           1629 non-null   object 
 14  tagline           557 non-null    object 
 15  actors            1624 non-null   object 
 16  wins_nominations  707 non-null    object 


In [21]:
ipl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   ID               950 non-null    int64  
 1   City             899 non-null    object 
 2   Date             950 non-null    object 
 3   Season           950 non-null    object 
 4   MatchNumber      950 non-null    object 
 5   Team1            950 non-null    object 
 6   Team2            950 non-null    object 
 7   Venue            950 non-null    object 
 8   TossWinner       950 non-null    object 
 9   TossDecision     950 non-null    object 
 10  SuperOver        946 non-null    object 
 11  WinningTeam      946 non-null    object 
 12  WonBy            950 non-null    object 
 13  Margin           932 non-null    float64
 14  method           19 non-null     object 
 15  Player_of_Match  946 non-null    object 
 16  Team1Players     950 non-null    object 
 17  Team2Players    

### describe

similar as series, give us description of all the numeric data

In [22]:
movies.describe()

is_adult  year_of_release  imdb_rating     imdb_votes
count    1629.0      1629.000000  1629.000000    1629.000000
mean        0.0      2010.263966     5.557459    5384.263352
std         0.0         5.381542     1.567609   14552.103231
min         0.0      2001.000000     0.000000       0.000000
25%         0.0      2005.000000     4.400000     233.000000
50%         0.0      2011.000000     5.600000    1000.000000
75%         0.0      2015.000000     6.800000    4287.000000
max         0.0      2019.000000     9.400000  310481.000000

In [23]:
ipl.describe()

ID      Margin
count  9.500000e+02  932.000000
mean   8.304852e+05   17.056867
std    3.375678e+05   21.633109
min    3.359820e+05    1.000000
25%    5.012612e+05    6.000000
50%    8.297380e+05    8.000000
75%    1.175372e+06   19.000000
max    1.312200e+06  146.000000

### isnull

To check if any missing values present

In [24]:
movies.isnull()

title_x  imdb_id  poster_path  wiki_link  title_y  original_title  \
0       False    False        False      False    False           False   
1       False    False         True      False    False           False   
2       False    False        False      False    False           False   
3       False    False        False      False    False           False   
4       False    False         True      False    False           False   
...       ...      ...          ...        ...      ...             ...   
1624    False    False        False      False    False           False   
1625    False    False        False      False    False           False   
1626    False    False         True      False    False           False   
1627    False    False        False      False    False           False   
1628    False    False        False      False    False           False   

      is_adult  year_of_release  runtime  genres  imdb_rating  imdb_votes  \
0        False            False    False   False        False       False   
1        False            False    False   False        False       False   
2        False            False    False   False        False       False   
3        False            False    False   False        False       False   
4        False            False    False   False        False       False   
...        ...              ...      ...     ...          ...         ...   
1624     False            False    False   False        False       False   
1625     False            False    False   False        False       False   
1626     False            False    False   False        False       False   
1627     False            False    False   False        False       False   
1628     False            False    False   False        False       False   

      story  summary  tagline  actors  wins_nominations  release_date  
0     False    False     True   False             False         False  
1     False    False     True   False              True         False  
2     False    False     True   False              True         False  
3     False    False     True   False              True         False  
4     False    False     True   False             False         False  
...     ...      ...      ...     ...               ...           ...  
1624  False    False     True   False              True         False  
1625  False    False     True   False              True         False  
1626  False    False     True   False              True          True  
1627  False    False     True   False              True         False  
1628  False    False     True   False              True         False  

[1629 rows x 18 columns]

In [25]:
movies.isnull().sum()

title_x                0
imdb_id                0
poster_path          103
wiki_link              0
title_y                0
original_title         0
is_adult               0
year_of_release        0
runtime                0
genres                 0
imdb_rating            0
imdb_votes             0
story                 20
summary                0
tagline             1072
actors                 5
wins_nominations     922
release_date         107
dtype: int64

### duplicated

To check the duplicate values

In [26]:
movies.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...  
1624    False
1625    False
1626    False
1627    False
1628    False
Length: 1629, dtype: bool

In [27]:
movies.duplicated().sum()

0

### rename

To rename any column

In [28]:
students

iq  marks  package
0  100     80       10
1   90     70        7
2  120    100       14
3   80     50        2
4    0      0        0
5    0      0        0

Providing new names for the columns using a dictionary.

In [29]:
students.rename(columns={'iq':'Scale','marks':'Score','package':'Lpa'})

Scale  Score  Lpa
0    100     80   10
1     90     70    7
2    120    100   14
3     80     50    2
4      0      0    0
5      0      0    0

But these changes are not permanent, to make permanent changes pass inplace=True

In [30]:
students

iq  marks  package
0  100     80       10
1   90     70        7
2  120    100       14
3   80     50        2
4    0      0        0
5    0      0        0

In [31]:
students.rename(columns={'iq':'Scale','marks':'Score','package':'Lpa'},inplace=True)

In [32]:
students

Scale  Score  Lpa
0    100     80   10
1     90     70    7
2    120    100   14
3     80     50    2
4      0      0    0
5      0      0    0

# Mathematical Functions

### sum()

This would apply sum on every columns, integers added, strings concatenated, arise error when there are string and integers both presented in a column(in this case maybe nan values)

In [33]:
ipl.sum()

TypeError: can only concatenate str (not "int") to str

In [ ]:
students.sum()

Scale    390
Score    300
Lpa       33
dtype: int64

Operations performed row wise if axis changed

In [ ]:
movies.sum(axis=1)

TypeError: can only concatenate str (not "int") to str

In [ ]:
students.sum(axis=1)

TypeError: can only concatenate str (not "int") to str

In [ ]:
student_dict = {
    'iq':[100,90,120,80,0,0],
    'marks':[80,70,100,50,0,0],
    'package':[10,7,14,2,0,0]
}

In [ ]:
student_dict = pd.DataFrame(student_dict)

In [ ]:
student_dict.sum()

iq         390
marks      300
package     33
dtype: int64

In [ ]:
student_dict.sum(axis=1)

0    190
1    167
2    234
3    132
4      0
5      0
dtype: int64

### mean

In [ ]:
student_dict.mean()

iq         65.0
marks      50.0
package     5.5
dtype: float64

### min()

In [ ]:
student_dict.min()

iq         0
marks      0
package    0
dtype: int64

Row-wise

In [ ]:
student_dict.min(axis=1)

0    10
1     7
2    14
3     2
4     0
5     0
dtype: int64

### max()

In [ ]:
student_dict.max()

iq         120
marks      100
package     14
dtype: int64

Row-wise

In [ ]:
student_dict.max(axis=1)

0    100
1     90
2    120
3     80
4      0
5      0
dtype: int64

### Standerd division

In [ ]:
student_dict.std()

iq         52.057660
marks      41.952354
package     5.787918
dtype: float64

Row-wise

In [ ]:
student_dict.std(axis=1)

0    47.258156
1    43.316663
2    56.320511
3    39.344631
4     0.000000
5     0.000000
dtype: float64

### variance

In [ ]:
student_dict.var()

iq         2710.0
marks      1760.0
package      33.5
dtype: float64

Row-wise

In [ ]:
student_dict.var(axis=1)

0    2233.333333
1    1876.333333
2    3172.000000
3    1548.000000
4       0.000000
5       0.000000
dtype: float64

# Selecting one column from a DataFrame

If we wanna select for example name of the moveis

In [ ]:
movies

title_x     imdb_id  \
0                 Uri: The Surgical Strike   tt8291224   
1                            Battalion 609   tt9472208   
2     The Accidental Prime Minister (film)   tt6986710   
3                          Why Cheat India   tt8108208   
4                          Evening Shadows   tt6028796   
...                                    ...         ...   
1624                 Tera Mera Saath Rahen   tt0301250   
1625                  Yeh Zindagi Ka Safar   tt0298607   
1626                       Sabse Bada Sukh   tt0069204   
1627                                 Daaka  tt10833860   
1628                              Humsafar   tt2403201   

                                            poster_path  \
0     https://upload.wikimedia.org/wikipedia/en/thum...   
1                                                   NaN   
2     https://upload.wikimedia.org/wikipedia/en/thum...   
3     https://upload.wikimedia.org/wikipedia/en/thum...   
4                                                   NaN   
...                                                 ...   
1624  https://upload.wikimedia.org/wikipedia/en/2/2b...   
1625  https://upload.wikimedia.org/wikipedia/en/thum...   
1626                                                NaN   
1627  https://upload.wikimedia.org/wikipedia/en/thum...   
1628  https://upload.wikimedia.org/wikipedia/en/thum...   

                                              wiki_link  \
0     https://en.wikipedia.org/wiki/Uri:_The_Surgica...   
1           https://en.wikipedia.org/wiki/Battalion_609   
2     https://en.wikipedia.org/wiki/The_Accidental_P...   
3         https://en.wikipedia.org/wiki/Why_Cheat_India   
4         https://en.wikipedia.org/wiki/Evening_Shadows   
...                                                 ...   
1624  https://en.wikipedia.org/wiki/Tera_Mera_Saath_...   
1625  https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...   
1626      https://en.wikipedia.org/wiki/Sabse_Bada_Sukh   
1627                https://en.wikipedia.org/wiki/Daaka   
1628             https://en.wikipedia.org/wiki/Humsafar   

                            title_y                 original_title  is_adult  \
0          Uri: The Surgical Strike       Uri: The Surgical Strike         0   
1                     Battalion 609                  Battalion 609         0   
2     The Accidental Prime Minister  The Accidental Prime Minister         0   
3                   Why Cheat India                Why Cheat India         0   
4                   Evening Shadows                Evening Shadows         0   
...                             ...                            ...       ...   
1624          Tera Mera Saath Rahen          Tera Mera Saath Rahen         0   
1625           Yeh Zindagi Ka Safar           Yeh Zindagi Ka Safar         0   
1626                Sabse Bada Sukh                Sabse Bada Sukh         0   
1627                          Daaka                          Daaka         0   
1628                       Humsafar                       Humsafar         0   

      year_of_release runtime            genres  imdb_rating  imdb_votes  \
0                2019     138  Action|Drama|War          8.4       35112   
1                2019     131               War          4.1          73   
2                2019     112   Biography|Drama          6.1        5549   
3                2019     121       Crime|Drama          6.0        1891   
4                2018     102             Drama          7.3         280   
...               ...     ...               ...          ...         ...   
1624             2001     148             Drama          4.9         278   
1625             2001     146             Drama          3.0         133   
1626             2018      \N      Comedy|Drama          6.1          13   
1627             2019     136            Action          7.4          38   
1628             2011      35     Drama|Romance          9.0        2968   

                                              

We'll use name of the dataframe and pass the name of the column that we want inside a square bracket, this would return a series of that column

In [ ]:
movies['title_x']

0                   Uri: The Surgical Strike
1                              Battalion 609
2       The Accidental Prime Minister (film)
3                            Why Cheat India
4                            Evening Shadows
                        ...                 
1624                   Tera Mera Saath Rahen
1625                    Yeh Zindagi Ka Safar
1626                         Sabse Bada Sukh
1627                                   Daaka
1628                                Humsafar
Name: title_x, Length: 1629, dtype: object

In [ ]:
type(movies['title_x'])

pandas.core.series.Series

In [ ]:
ipl

ID        City        Date   Season  MatchNumber  \
0    1312200   Ahmedabad  2022-05-29     2022        Final   
1    1312199   Ahmedabad  2022-05-27     2022  Qualifier 2   
2    1312198     Kolkata  2022-05-25     2022   Eliminator   
3    1312197     Kolkata  2022-05-24     2022  Qualifier 1   
4    1304116      Mumbai  2022-05-22     2022           70   
..       ...         ...         ...      ...          ...   
945   335986     Kolkata  2008-04-20  2007/08            4   
946   335985      Mumbai  2008-04-20  2007/08            5   
947   335984       Delhi  2008-04-19  2007/08            3   
948   335983  Chandigarh  2008-04-19  2007/08            2   
949   335982   Bangalore  2008-04-18  2007/08            1   

                           Team1                        Team2  \
0               Rajasthan Royals               Gujarat Titans   
1    Royal Challengers Bangalore             Rajasthan Royals   
2    Royal Challengers Bangalore         Lucknow Super Giants   
3               Rajasthan Royals               Gujarat Titans   
4            Sunrisers Hyderabad                 Punjab Kings   
..                           ...                          ...   
945        Kolkata Knight Riders              Deccan Chargers   
946               Mumbai Indians  Royal Challengers Bangalore   
947             Delhi Daredevils             Rajasthan Royals   
948              Kings XI Punjab          Chennai Super Kings   
949  Royal Challengers Bangalore        Kolkata Knight Riders   

                                          Venue                   TossWinner  \
0              Narendra Modi Stadium, Ahmedabad             Rajasthan Royals   
1              Narendra Modi Stadium, Ahmedabad             Rajasthan Royals   
2                         Eden Gardens, Kolkata         Lucknow Super Giants   
3                         Eden Gardens, Kolkata               Gujarat Titans   
4                      Wankhede Stadium, Mumbai          Sunrisers Hyderabad   
..                                          ...                          ...   
945                                Eden Gardens              Deccan Chargers   
946                            Wankhede Stadium               Mumbai Indians   
947                            Feroz Shah Kotla             Rajasthan Royals   
948  Punjab Cricket Association Stadium, Mohali          Chennai Super Kings   
949                       M Chinnaswamy Stadium  Royal Challengers Bangalore   

    TossDecision SuperOver                  WinningTeam    WonBy  Margin  \
0            bat         N               Gujarat Titans  Wickets     7.0   
1          field         N             Rajasthan Royals  Wickets     7.0   
2          field         N  Royal Challengers Bangalore     Runs    14.0   
3          field         N               Gujarat Titans  Wickets     7.0   
4            bat         N                 Punjab Kings  Wickets     5.0   
..           ...       ...                          ...      ...     ...   
945          bat         N        Kolkata Knight Riders  Wickets     5.0   
946          bat         N  Royal Challengers Bangalore  Wickets     5.0   
947          bat         N             Delhi Daredevils  Wickets     9.0   
948          bat         N          Chennai Super Kings     Runs    33.0   
949        field         N        Kolkata Knight Riders     Runs   140.0   

    method Player_of_Match                                       Team1Players  \
0      NaN       HH Pandya  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...   
1      NaN      JC Buttler  ['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...   
2      NaN      RM Patidar  ['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...   
3      NaN       DA Miller  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...   
4      NaN   Harpreet Brar  ['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...   
..     ...             ...                                                ...   
945    NaN       DJ Hussey  ['WP Saha', 'BB

In [ ]:
ipl['Venue']

0                Narendra Modi Stadium, Ahmedabad
1                Narendra Modi Stadium, Ahmedabad
2                           Eden Gardens, Kolkata
3                           Eden Gardens, Kolkata
4                        Wankhede Stadium, Mumbai
                          ...                    
945                                  Eden Gardens
946                              Wankhede Stadium
947                              Feroz Shah Kotla
948    Punjab Cricket Association Stadium, Mohali
949                         M Chinnaswamy Stadium
Name: Venue, Length: 950, dtype: object

# Selecting multiple column from a DataFrame

If we wanna select for example name of the moveis, year of relese, and story. We're gonna use fancy indexing

In [ ]:
movies

title_x     imdb_id  \
0                 Uri: The Surgical Strike   tt8291224   
1                            Battalion 609   tt9472208   
2     The Accidental Prime Minister (film)   tt6986710   
3                          Why Cheat India   tt8108208   
4                          Evening Shadows   tt6028796   
...                                    ...         ...   
1624                 Tera Mera Saath Rahen   tt0301250   
1625                  Yeh Zindagi Ka Safar   tt0298607   
1626                       Sabse Bada Sukh   tt0069204   
1627                                 Daaka  tt10833860   
1628                              Humsafar   tt2403201   

                                            poster_path  \
0     https://upload.wikimedia.org/wikipedia/en/thum...   
1                                                   NaN   
2     https://upload.wikimedia.org/wikipedia/en/thum...   
3     https://upload.wikimedia.org/wikipedia/en/thum...   
4                                                   NaN   
...                                                 ...   
1624  https://upload.wikimedia.org/wikipedia/en/2/2b...   
1625  https://upload.wikimedia.org/wikipedia/en/thum...   
1626                                                NaN   
1627  https://upload.wikimedia.org/wikipedia/en/thum...   
1628  https://upload.wikimedia.org/wikipedia/en/thum...   

                                              wiki_link  \
0     https://en.wikipedia.org/wiki/Uri:_The_Surgica...   
1           https://en.wikipedia.org/wiki/Battalion_609   
2     https://en.wikipedia.org/wiki/The_Accidental_P...   
3         https://en.wikipedia.org/wiki/Why_Cheat_India   
4         https://en.wikipedia.org/wiki/Evening_Shadows   
...                                                 ...   
1624  https://en.wikipedia.org/wiki/Tera_Mera_Saath_...   
1625  https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...   
1626      https://en.wikipedia.org/wiki/Sabse_Bada_Sukh   
1627                https://en.wikipedia.org/wiki/Daaka   
1628             https://en.wikipedia.org/wiki/Humsafar   

                            title_y                 original_title  is_adult  \
0          Uri: The Surgical Strike       Uri: The Surgical Strike         0   
1                     Battalion 609                  Battalion 609         0   
2     The Accidental Prime Minister  The Accidental Prime Minister         0   
3                   Why Cheat India                Why Cheat India         0   
4                   Evening Shadows                Evening Shadows         0   
...                             ...                            ...       ...   
1624          Tera Mera Saath Rahen          Tera Mera Saath Rahen         0   
1625           Yeh Zindagi Ka Safar           Yeh Zindagi Ka Safar         0   
1626                Sabse Bada Sukh                Sabse Bada Sukh         0   
1627                          Daaka                          Daaka         0   
1628                       Humsafar                       Humsafar         0   

      year_of_release runtime            genres  imdb_rating  imdb_votes  \
0                2019     138  Action|Drama|War          8.4       35112   
1                2019     131               War          4.1          73   
2                2019     112   Biography|Drama          6.1        5549   
3                2019     121       Crime|Drama          6.0        1891   
4                2018     102             Drama          7.3         280   
...               ...     ...               ...          ...         ...   
1624             2001     148             Drama          4.9         278   
1625             2001     146             Drama          3.0         133   
1626             2018      \N      Comedy|Drama          6.1          13   
1627             2019     136            Action          7.4          38   
1628             2011      35     Drama|Romance          9.0        2968   

                                              

So we're gonna pass a 2D list of name of the columns that we want. This would return a dataframe of columns.

Return a series if only one column is fletched, DataFrame if multiple columns are fletched.

In [ ]:
movies[['title_x','year_of_release','story']]

title_x  year_of_release  \
0                 Uri: The Surgical Strike             2019   
1                            Battalion 609             2019   
2     The Accidental Prime Minister (film)             2019   
3                          Why Cheat India             2019   
4                          Evening Shadows             2018   
...                                    ...              ...   
1624                 Tera Mera Saath Rahen             2001   
1625                  Yeh Zindagi Ka Safar             2001   
1626                       Sabse Bada Sukh             2018   
1627                                 Daaka             2019   
1628                              Humsafar             2011   

                                                  story  
0     Divided over five chapters  the film chronicle...  
1     The story revolves around a cricket match betw...  
2     Based on the memoir by Indian policy analyst S...  
3     The movie focuses on existing malpractices in ...  
4     While gay rights and marriage equality has bee...  
...                                                 ...  
1624  Raj Dixit lives with his younger brother  Rahu...  
1625  Hindi pop-star  Sarina Devan  lives a wealthy ...  
1626  Village born Lalloo re-locates to Bombay  and ...  
1627  Shinda tries robbing a bank so he can be wealt...  
1628  Sara and Ashar are childhood friends who share...  

[1629 rows x 3 columns]

In [ ]:
type(movies[['title_x','year_of_release','story']])

pandas.core.frame.DataFrame

Also order matters here in terms of projecting the columns

In [ ]:
movies[['story','title_x','year_of_release']]

story  \
0     Divided over five chapters  the film chronicle...   
1     The story revolves around a cricket match betw...   
2     Based on the memoir by Indian policy analyst S...   
3     The movie focuses on existing malpractices in ...   
4     While gay rights and marriage equality has bee...   
...                                                 ...   
1624  Raj Dixit lives with his younger brother  Rahu...   
1625  Hindi pop-star  Sarina Devan  lives a wealthy ...   
1626  Village born Lalloo re-locates to Bombay  and ...   
1627  Shinda tries robbing a bank so he can be wealt...   
1628  Sara and Ashar are childhood friends who share...   

                                   title_x  year_of_release  
0                 Uri: The Surgical Strike             2019  
1                            Battalion 609             2019  
2     The Accidental Prime Minister (film)             2019  
3                          Why Cheat India             2019  
4                          Evening Shadows             2018  
...                                    ...              ...  
1624                 Tera Mera Saath Rahen             2001  
1625                  Yeh Zindagi Ka Safar             2001  
1626                       Sabse Bada Sukh             2018  
1627                                 Daaka             2019  
1628                              Humsafar             2011  

[1629 rows x 3 columns]

Example 2: if we wanna find out all the matches played between what teams and who win

In [ ]:
ipl[['Team1','Team2','WinningTeam']]

Team1                        Team2  \
0               Rajasthan Royals               Gujarat Titans   
1    Royal Challengers Bangalore             Rajasthan Royals   
2    Royal Challengers Bangalore         Lucknow Super Giants   
3               Rajasthan Royals               Gujarat Titans   
4            Sunrisers Hyderabad                 Punjab Kings   
..                           ...                          ...   
945        Kolkata Knight Riders              Deccan Chargers   
946               Mumbai Indians  Royal Challengers Bangalore   
947             Delhi Daredevils             Rajasthan Royals   
948              Kings XI Punjab          Chennai Super Kings   
949  Royal Challengers Bangalore        Kolkata Knight Riders   

                     WinningTeam  
0                 Gujarat Titans  
1               Rajasthan Royals  
2    Royal Challengers Bangalore  
3                 Gujarat Titans  
4                   Punjab Kings  
..                           ...  
945        Kolkata Knight Riders  
946  Royal Challengers Bangalore  
947             Delhi Daredevils  
948          Chennai Super Kings  
949        Kolkata Knight Riders  

[950 rows x 3 columns]

# Selecting rows from a DataFrame

In [ ]:
student = {
    'name':['nitish','ankit','rupesh','rishabh','amit','ankita'],
    'iq':[100,90,120,80,0,0],
    'marks':[80,70,100,50,0,0],
    'package':[10,7,14,2,0,0]
}

In [ ]:
student = pd.DataFrame(student)

In [ ]:
student

name   iq  marks  package
0   nitish  100     80       10
1    ankit   90     70        7
2   rupesh  120    100       14
3  rishabh   80     50        2
4     amit    0      0        0
5   ankita    0      0        0

To remove the pandas assigned indexes and make name column as index we can write this piece of code, we'll know about this code latter.

In [ ]:
student.set_index('name',inplace=True)
student

iq  marks  package
name                        
nitish   100     80       10
ankit     90     70        7
rupesh   120    100       14
rishabh   80     50        2
amit       0      0        0
ankita     0      0        0

### There are two ways to search rows

- **iloc** - searches using index positions
- **loc** - searches using index labels 

### iloc, index location

To fletch the first row we're provide an index position in iloc and this would return a series of that perticular row

In [ ]:
movies.iloc[0]

title_x                                      Uri: The Surgical Strike
imdb_id                                                     tt8291224
poster_path         https://upload.wikimedia.org/wikipedia/en/thum...
wiki_link           https://en.wikipedia.org/wiki/Uri:_The_Surgica...
title_y                                      Uri: The Surgical Strike
original_title                               Uri: The Surgical Strike
is_adult                                                            0
year_of_release                                                  2019
runtime                                                           138
genres                                               Action|Drama|War
imdb_rating                                                       8.4
imdb_votes                                                      35112
story               Divided over five chapters  the film chronicle...
summary             Indian army special forces execute a covert op...
tagline             

In [ ]:
type(movies.iloc[0])

pandas.core.series.Series

To fletch multiple rows using index, for example 0 to 5th, we'ii write [0:5] here last index is not included, works as python slicing, returns a dataframe

In [ ]:
movies.iloc[0:5]

title_x    imdb_id  \
0              Uri: The Surgical Strike  tt8291224   
1                         Battalion 609  tt9472208   
2  The Accidental Prime Minister (film)  tt6986710   
3                       Why Cheat India  tt8108208   
4                       Evening Shadows  tt6028796   

                                         poster_path  \
0  https://upload.wikimedia.org/wikipedia/en/thum...   
1                                                NaN   
2  https://upload.wikimedia.org/wikipedia/en/thum...   
3  https://upload.wikimedia.org/wikipedia/en/thum...   
4                                                NaN   

                                           wiki_link  \
0  https://en.wikipedia.org/wiki/Uri:_The_Surgica...   
1        https://en.wikipedia.org/wiki/Battalion_609   
2  https://en.wikipedia.org/wiki/The_Accidental_P...   
3      https://en.wikipedia.org/wiki/Why_Cheat_India   
4      https://en.wikipedia.org/wiki/Evening_Shadows   

                         title_y                 original_title  is_adult  \
0       Uri: The Surgical Strike       Uri: The Surgical Strike         0   
1                  Battalion 609                  Battalion 609         0   
2  The Accidental Prime Minister  The Accidental Prime Minister         0   
3                Why Cheat India                Why Cheat India         0   
4                Evening Shadows                Evening Shadows         0   

   year_of_release runtime            genres  imdb_rating  imdb_votes  \
0             2019     138  Action|Drama|War          8.4       35112   
1             2019     131               War          4.1          73   
2             2019     112   Biography|Drama          6.1        5549   
3             2019     121       Crime|Drama          6.0        1891   
4             2018     102             Drama          7.3         280   

                                               story  \
0  Divided over five chapters  the film chronicle...   
1  The story revolves around a cricket match betw...   
2  Based on the memoir by Indian policy analyst S...   
3  The movie focuses on existing malpractices in ...   
4  While gay rights and marriage equality has bee...   

                                             summary tagline  \
0  Indian army special forces execute a covert op...     NaN   
1  The story of Battalion 609 revolves around a c...     NaN   
2  Explores Manmohan Singh's tenure as the Prime ...     NaN   
3  The movie focuses on existing malpractices in ...     NaN   
4  Under the 'Evening Shadows'  truth often plays...     NaN   

                                              actors        wins_nominations  \
0  Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...                  4 wins   
1  Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...                     NaN   
2  Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...                     NaN   
3  Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...                     NaN   
4  Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...  17 wins & 1 nomination   

              release_date  
0    11 January 2019 (USA)  
1  11 January 2019 (India)  
2    11 January 2019 (USA)  
3    18 January 2019 (USA)  
4  11 January 2019 (India)

Similarly for alternate rows

In [ ]:
movies.iloc[5:17:2]

title_x    imdb_id  \
5         Soni (film)  tt6078866   
7          Bombairiya  tt4971258   
9    Thackeray (film)  tt7777196   
11          Gully Boy  tt2395469   
13      Total Dhamaal  tt7639372   
15  Badla (2019 film)  tt8130968   

                                          poster_path  \
5   https://upload.wikimedia.org/wikipedia/en/thum...   
7   https://upload.wikimedia.org/wikipedia/en/thum...   
9   https://upload.wikimedia.org/wikipedia/en/thum...   
11  https://upload.wikimedia.org/wikipedia/en/thum...   
13  https://upload.wikimedia.org/wikipedia/en/thum...   
15  https://upload.wikimedia.org/wikipedia/en/0/0c...   

                                          wiki_link        title_y  \
5         https://en.wikipedia.org/wiki/Soni_(film)           Soni   
7          https://en.wikipedia.org/wiki/Bombairiya     Bombairiya   
9    https://en.wikipedia.org/wiki/Thackeray_(film)      Thackeray   
11          https://en.wikipedia.org/wiki/Gully_Boy      Gully Boy   
13      https://en.wikipedia.org/wiki/Total_Dhamaal  Total Dhamaal   
15  https://en.wikipedia.org/wiki/Badla_(2019_film)          Badla   

   original_title  is_adult  year_of_release runtime                   genres  \
5            Soni         0             2018      97                    Drama   
7      Bombairiya         0             2019     104       Comedy|Crime|Drama   
9       Thackeray         0             2019     120          Biography|Drama   
11      Gully Boy         0             2019     153              Drama|Music   
13  Total Dhamaal         0             2019     130  Action|Adventure|Comedy   
15          Badla         0             2019     118      Crime|Drama|Mystery   

    imdb_rating  imdb_votes  \
5           7.2        1595   
7           4.3         295   
9           5.1        2301   
11          8.2       22440   
13          4.3        4817   
15          7.9       15499   

                                                story  \
5   Soni  a young policewoman in Delhi  and her su...   
7   It follows the story of Meghna  who gets embro...   
9   Balasaheb Thackrey works as a cartoonist for a...   
11  Gully Boy is a film about a 22-year-old boy "M...   
13  Total Dhamaal is the third instalment in the D...   
15  Naina Sethi a successful entrepreneur finds he...   

                                              summary  \
5   While fighting crimes against women in Delhi  ...   
7   It follows the story of Meghna  who gets embro...   
9   Biographical account of Shiv Sena Supremo  Bal...   
11  A coming-of-age story based on the lives of st...   
13  A group of people learn about a hidden treasur...   
15  A dynamic young entrepreneur finds herself loc...   

                                  tagline  \
5                                     NaN   
7   They didn't mean to change the world.   
9                                     NaN   
11                      Apna Time Aayega!   
13             The Wildest Adventure Ever   
15                                    NaN   

                                               actors        wins_nominations  \
5   Geetika Vidya Ohlyan|Saloni Batra|Vikas Shukla...  3 wins & 5 nominations   
7   Radhika Apte|Akshay Oberoi|Siddhanth Kapoor|Ra...                     NaN   
9   Nawazuddin Siddiqui|Amrita Rao|Abdul Quadir Am...                     NaN   
11  Ranveer Singh|Alia Bhatt|Siddhant Chaturvedi|V...  6 wins & 3 nominations   
13  Ajay Devgn|Madhuri Dixit|Anil Kapoor|Riteish D...                     NaN   
15  Amitabh Bachchan|Taapsee Pannu|Amrita Singh|An...                   1 win   

                release_date  
5      18 January 2019 (USA)  
7    18 January 2019 (India)  
9    25 January 2019 (India)  
11    14 February 2019 (USA)  
13  22 February 2019 (India)  
15      8 March 2019 (India)

For fancy indexing, we'll pass a list of the rows that we wanna fletch

In [ ]:
movies.iloc[[5,7,9]]

title_x    imdb_id  \
5       Soni (film)  tt6078866   
7        Bombairiya  tt4971258   
9  Thackeray (film)  tt7777196   

                                         poster_path  \
5  https://upload.wikimedia.org/wikipedia/en/thum...   
7  https://upload.wikimedia.org/wikipedia/en/thum...   
9  https://upload.wikimedia.org/wikipedia/en/thum...   

                                        wiki_link     title_y original_title  \
5       https://en.wikipedia.org/wiki/Soni_(film)        Soni           Soni   
7        https://en.wikipedia.org/wiki/Bombairiya  Bombairiya     Bombairiya   
9  https://en.wikipedia.org/wiki/Thackeray_(film)   Thackeray      Thackeray   

   is_adult  year_of_release runtime              genres  imdb_rating  \
5         0             2018      97               Drama          7.2   
7         0             2019     104  Comedy|Crime|Drama          4.3   
9         0             2019     120     Biography|Drama          5.1   

   imdb_votes                                              story  \
5        1595  Soni  a young policewoman in Delhi  and her su...   
7         295  It follows the story of Meghna  who gets embro...   
9        2301  Balasaheb Thackrey works as a cartoonist for a...   

                                             summary  \
5  While fighting crimes against women in Delhi  ...   
7  It follows the story of Meghna  who gets embro...   
9  Biographical account of Shiv Sena Supremo  Bal...   

                                 tagline  \
5                                    NaN   
7  They didn't mean to change the world.   
9                                    NaN   

                                              actors        wins_nominations  \
5  Geetika Vidya Ohlyan|Saloni Batra|Vikas Shukla...  3 wins & 5 nominations   
7  Radhika Apte|Akshay Oberoi|Siddhanth Kapoor|Ra...                     NaN   
9  Nawazuddin Siddiqui|Amrita Rao|Abdul Quadir Am...                     NaN   

              release_date  
5    18 January 2019 (USA)  
7  18 January 2019 (India)  
9  25 January 2019 (India)

### loc, location, indexing using labels

In [ ]:
student

iq  marks  package
name                        
nitish   100     80       10
ankit     90     70        7
rupesh   120    100       14
rishabh   80     50        2
amit       0      0        0
ankita     0      0        0

In [ ]:
student.loc['rupesh']

iq         120
marks      100
package     14
Name: rupesh, dtype: int64

For multiple lables we'll pass a range, last row is included here.

In [ ]:
student.loc['nitish':'rishabh']

iq  marks  package
name                        
nitish   100     80       10
ankit     90     70        7
rupesh   120    100       14
rishabh   80     50        2

Others indexing also works as well

Similarly iloc works as well

In [ ]:
student.iloc[0]

iq         100
marks       80
package     10
Name: nitish, dtype: int64

# Selecting both rows and columns together

### using iloc

Suppose if we wanna fltch first 3 columns for first 3 rows

In [ ]:
movies.iloc[0:3,0:3]

title_x    imdb_id  \
0              Uri: The Surgical Strike  tt8291224   
1                         Battalion 609  tt9472208   
2  The Accidental Prime Minister (film)  tt6986710   

                                         poster_path  
0  https://upload.wikimedia.org/wikipedia/en/thum...  
1                                                NaN  
2  https://upload.wikimedia.org/wikipedia/en/thum...

### using loc

Let's do the same thing using loc

In [ ]:
movies.loc[0:2,'title_x':'poster_path']

title_x    imdb_id  \
0              Uri: The Surgical Strike  tt8291224   
1                         Battalion 609  tt9472208   
2  The Accidental Prime Minister (film)  tt6986710   

                                         poster_path  
0  https://upload.wikimedia.org/wikipedia/en/thum...  
1                                                NaN  
2  https://upload.wikimedia.org/wikipedia/en/thum...

# Filtering a DataFrame

### Question 1: find all the final winners season wise

In [ ]:
ipl.head(2)

ID       City        Date Season  MatchNumber  \
0  1312200  Ahmedabad  2022-05-29   2022        Final   
1  1312199  Ahmedabad  2022-05-27   2022  Qualifier 2   

                         Team1             Team2  \
0             Rajasthan Royals    Gujarat Titans   
1  Royal Challengers Bangalore  Rajasthan Royals   

                              Venue        TossWinner TossDecision SuperOver  \
0  Narendra Modi Stadium, Ahmedabad  Rajasthan Royals          bat         N   
1  Narendra Modi Stadium, Ahmedabad  Rajasthan Royals        field         N   

        WinningTeam    WonBy  Margin method Player_of_Match  \
0    Gujarat Titans  Wickets     7.0    NaN       HH Pandya   
1  Rajasthan Royals  Wickets     7.0    NaN      JC Buttler   

                                        Team1Players  \
0  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...   
1  ['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...   

                                        Team2Players      Umpire1      Umpire2  
0  ['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...  CB Gaffaney  Nitin Menon  
1  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...  CB Gaffaney  Nitin Menon

So first, here we need to fletch all the final matches.

In [ ]:
ipl['MatchNumber']=='Final'

0       True
1      False
2      False
3      False
4      False
       ...  
945    False
946    False
947    False
948    False
949    False
Name: MatchNumber, Length: 950, dtype: bool

Now if we fletch this series on the actual dataframe, we're gonna find all the final matches

In [ ]:
ipl[ipl['MatchNumber']=='Final']

ID          City        Date   Season MatchNumber  \
0    1312200     Ahmedabad  2022-05-29     2022       Final   
74   1254117         Dubai  2021-10-15     2021       Final   
134  1237181           NaN  2020-11-10  2020/21       Final   
194  1181768     Hyderabad  2019-05-12     2019       Final   
254  1136620        Mumbai  2018-05-27     2018       Final   
314  1082650     Hyderabad  2017-05-21     2017       Final   
373   981019     Bangalore  2016-05-29     2016       Final   
433   829823       Kolkata  2015-05-24     2015       Final   
492   734049     Bangalore  2014-06-01     2014       Final   
552   598073       Kolkata  2013-05-26     2013       Final   
628   548381       Chennai  2012-05-27     2012       Final   
702   501271       Chennai  2011-05-28     2011       Final   
775   419165        Mumbai  2010-04-25  2009/10       Final   
835   392239  Johannesburg  2009-05-24     2009       Final   
892   336040        Mumbai  2008-06-01  2007/08       Final   

                           Team1                        Team2  \
0               Rajasthan Royals               Gujarat Titans   
74           Chennai Super Kings        Kolkata Knight Riders   
134               Delhi Capitals               Mumbai Indians   
194               Mumbai Indians          Chennai Super Kings   
254          Sunrisers Hyderabad          Chennai Super Kings   
314               Mumbai Indians       Rising Pune Supergiant   
373  Royal Challengers Bangalore          Sunrisers Hyderabad   
433               Mumbai Indians          Chennai Super Kings   
492        Kolkata Knight Riders              Kings XI Punjab   
552          Chennai Super Kings               Mumbai Indians   
628        Kolkata Knight Riders          Chennai Super Kings   
702          Chennai Super Kings  Royal Challengers Bangalore   
775          Chennai Super Kings               Mumbai Indians   
835  Royal Challengers Bangalore              Deccan Chargers   
892          Chennai Super Kings             Rajasthan Royals   

                                         Venue                   TossWinner  \
0             Narendra Modi Stadium, Ahmedabad             Rajasthan Royals   
74         Dubai International Cricket Stadium        Kolkata Knight Riders   
134        Dubai International Cricket Stadium               Delhi Capitals   
194         Rajiv Gandhi International Stadium               Mumbai Indians   
254                           Wankhede Stadium          Chennai Super Kings   
314  Rajiv Gandhi International Stadium, Uppal               Mumbai Indians   
373                      M Chinnaswamy Stadium          Sunrisers Hyderabad   
433                               Eden Gardens          Chennai Super Kings   
492                      M Chinnaswamy Stadium        Kolkata Knight Riders   
552                               Eden Gardens               Mumbai Indians   
628            MA Chidambaram Stadium, Chepauk          Chennai Super Kings   
702            MA Chidambaram Stadium, Chepauk          Chennai Super Kings   
775                 Dr DY Patil Sports Academy          Chennai Super Kings   
835                      New Wanderers Stadium  Royal Challengers Bangalore   
892                 Dr DY Patil Sports Academy             Rajasthan Royals   

    TossDecision SuperOver            WinningTeam    WonBy  Margin method  \
0            bat         N         Gujarat Titans  Wickets     7.0    NaN   
74         field         N    Chennai Super Kings     Runs    27.0    NaN   
134          bat         N         Mumbai Indians  Wickets     5.0    NaN   
194          bat         N         Mumbai Indians     Runs     1.0    NaN   
254        field         N    Chennai Super Kings  Wickets     8.0    NaN   
314          bat         N         Mumbai Indians     Runs     1.0    NaN   
373          bat         N    Sunrisers Hyderabad     Runs     8.0    NaN   
433        field         N         Mumbai Indians     Runs    41.0    NaN   
49

Now we only need Season and WinningTeam

In [ ]:
final = ipl[ipl['MatchNumber']=='Final']

In [ ]:
final[['Season','WinningTeam']]

Season            WinningTeam
0       2022         Gujarat Titans
74      2021    Chennai Super Kings
134  2020/21         Mumbai Indians
194     2019         Mumbai Indians
254     2018    Chennai Super Kings
314     2017         Mumbai Indians
373     2016    Sunrisers Hyderabad
433     2015         Mumbai Indians
492     2014  Kolkata Knight Riders
552     2013         Mumbai Indians
628     2012  Kolkata Knight Riders
702     2011    Chennai Super Kings
775  2009/10    Chennai Super Kings
835     2009        Deccan Chargers
892  2007/08       Rajasthan Royals

We can also write this whole code in a single line

In [ ]:
ipl[ipl['MatchNumber']=='Final'][['Season','WinningTeam']]

Season            WinningTeam
0       2022         Gujarat Titans
74      2021    Chennai Super Kings
134  2020/21         Mumbai Indians
194     2019         Mumbai Indians
254     2018    Chennai Super Kings
314     2017         Mumbai Indians
373     2016    Sunrisers Hyderabad
433     2015         Mumbai Indians
492     2014  Kolkata Knight Riders
552     2013         Mumbai Indians
628     2012  Kolkata Knight Riders
702     2011    Chennai Super Kings
775  2009/10    Chennai Super Kings
835     2009        Deccan Chargers
892  2007/08       Rajasthan Royals

### Question 2: How many super over finishes have occured?

In [ ]:
ipl[ipl['SuperOver']== 'Y'].shape

(14, 20)

Since the first item is row

In [ ]:
ipl[ipl['SuperOver']== 'Y'].shape[0]

14

In [ ]:
ipl[ipl['SuperOver']== 'Y'].count()

ID                 14
City               11
Date               14
Season             14
MatchNumber        14
Team1              14
Team2              14
Venue              14
TossWinner         14
TossDecision       14
SuperOver          14
WinningTeam        14
WonBy              14
Margin              0
method              0
Player_of_Match    14
Team1Players       14
Team2Players       14
Umpire1            14
Umpire2            14
dtype: int64

### Question 3: How many matches has CSK won in Kolkata?

In [34]:
ipl.head(2)

ID       City        Date Season  MatchNumber  \
0  1312200  Ahmedabad  2022-05-29   2022        Final   
1  1312199  Ahmedabad  2022-05-27   2022  Qualifier 2   

                         Team1             Team2  \
0             Rajasthan Royals    Gujarat Titans   
1  Royal Challengers Bangalore  Rajasthan Royals   

                              Venue        TossWinner TossDecision SuperOver  \
0  Narendra Modi Stadium, Ahmedabad  Rajasthan Royals          bat         N   
1  Narendra Modi Stadium, Ahmedabad  Rajasthan Royals        field         N   

        WinningTeam    WonBy  Margin method Player_of_Match  \
0    Gujarat Titans  Wickets     7.0    NaN       HH Pandya   
1  Rajasthan Royals  Wickets     7.0    NaN      JC Buttler   

                                        Team1Players  \
0  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...   
1  ['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...   

                                        Team2Players      Umpire1      Umpire2  
0  ['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...  CB Gaffaney  Nitin Menon  
1  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...  CB Gaffaney  Nitin Menon

In [35]:
ipl[ipl['City']=='Kolkata']['WinningTeam']=='Chennai Super Kings'

2      False
3      False
207    False
211    False
219    False
       ...  
908     True
915    False
922    False
934    False
945    False
Name: WinningTeam, Length: 79, dtype: bool

In [37]:
ipl['WinningTeam']=='Chennai Super Kings'

0      False
1      False
2      False
3      False
4      False
       ...  
945    False
946    False
947    False
948     True
949    False
Name: WinningTeam, Length: 950, dtype: bool

In [ ]:
Ans3 = ipl[ipl['City']=='Kolkata']['WinningTeam']=='Chennai Super Kings'

In [ ]:
Ans3.sum()

5

Another way to solve this problem: Using two condition together ,city and winning team

In [ ]:
ipl[(ipl['City']=='Kolkata')&(ipl['WinningTeam']=='Chennai Super Kings')]

ID     City        Date   Season MatchNumber                  Team1  \
224  1178404  Kolkata  2019-04-14     2019          29  Kolkata Knight Riders   
602   598022  Kolkata  2013-04-20     2013          26  Kolkata Knight Riders   
641   548368  Kolkata  2012-05-14     2012          63  Kolkata Knight Riders   
827   419113  Kolkata  2010-03-16  2009/10           8  Kolkata Knight Riders   
908   336025  Kolkata  2008-05-18  2007/08          41  Kolkata Knight Riders   

                   Team2         Venue             TossWinner TossDecision  \
224  Chennai Super Kings  Eden Gardens    Chennai Super Kings        field   
602  Chennai Super Kings  Eden Gardens  Kolkata Knight Riders          bat   
641  Chennai Super Kings  Eden Gardens    Chennai Super Kings        field   
827  Chennai Super Kings  Eden Gardens    Chennai Super Kings          bat   
908  Chennai Super Kings  Eden Gardens  Kolkata Knight Riders          bat   

    SuperOver          WinningTeam    WonBy  Margin method Player_of_Match  \
224         N  Chennai Super Kings  Wickets     5.0    NaN     Imran Tahir   
602         N  Chennai Super Kings  Wickets     4.0    NaN       RA Jadeja   
641         N  Chennai Super Kings  Wickets     5.0    NaN      MEK Hussey   
827         N  Chennai Super Kings     Runs    55.0    NaN        MS Dhoni   
908         N  Chennai Super Kings     Runs     3.0    D/L         M Ntini   

                                          Team1Players  \
224  ['CA Lynn', 'SP Narine', 'N Rana', 'RV Uthappa...   
602  ['G Gambhir', 'YK Pathan', 'JH Kallis', 'EJG M...   
641  ['G Gambhir', 'BB McCullum', 'JH Kallis', 'MK ...   
827  ['BJ Hodge', 'MK Tiwary', 'SC Ganguly', 'WP Sa...   
908  ['Salman Butt', 'Mohammad Hafeez', 'SC Ganguly...   

                                          Team2Players          Umpire1  \
224  ['SR Watson', 'F du Plessis', 'SK Raina', 'AT ...        CK Nandan   
602  ['MEK Hussey', 'R Ashwin', 'M Vijay', 'SK Rain...        Asad Rauf   
641  ['MEK Hussey', 'M Vijay', 'SK Raina', 'F du Pl...        JD Cloete   
827  ['M Vijay', 'ML Hayden', 'SK Raina', 'S Badrin...  HDPK Dharmasena   
908  ['PA Patel', 'SP Fleming', 'S Vidyut', 'SK Rai...        Asad Rauf   

          Umpire2  
224     RJ Tucker  
602  AK Chaudhary  
641    SJA Taufel  
827     AM Saheba  
908   K Hariharan

In [ ]:
ipl[(ipl['City']=='Kolkata')&(ipl['WinningTeam']=='Chennai Super Kings')].shape[0]

5

### Question 4: What percent toss winner is a match winner?

In [ ]:
ipl.head(2)

ID       City        Date Season  MatchNumber  \
0  1312200  Ahmedabad  2022-05-29   2022        Final   
1  1312199  Ahmedabad  2022-05-27   2022  Qualifier 2   

                         Team1             Team2  \
0             Rajasthan Royals    Gujarat Titans   
1  Royal Challengers Bangalore  Rajasthan Royals   

                              Venue        TossWinner TossDecision SuperOver  \
0  Narendra Modi Stadium, Ahmedabad  Rajasthan Royals          bat         N   
1  Narendra Modi Stadium, Ahmedabad  Rajasthan Royals        field         N   

        WinningTeam    WonBy  Margin method Player_of_Match  \
0    Gujarat Titans  Wickets     7.0    NaN       HH Pandya   
1  Rajasthan Royals  Wickets     7.0    NaN      JC Buttler   

                                        Team1Players  \
0  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...   
1  ['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...   

                                        Team2Players      Umpire1      Umpire2  
0  ['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...  CB Gaffaney  Nitin Menon  
1  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...  CB Gaffaney  Nitin Menon

So, in this question we're gonna have to how many toss winner is winning team, to do that we'll compare both the columns.

In [ ]:
ipl['TossWinner']==ipl['WinningTeam']

0      False
1       True
2      False
3       True
4      False
       ...  
945    False
946    False
947    False
948     True
949    False
Length: 950, dtype: bool

Now if we impose this series on the actual, we'll find how many toss winner is winning team

In [ ]:
ipl[ipl['TossWinner']==ipl['WinningTeam']]

ID         City        Date   Season  MatchNumber  \
1    1312199    Ahmedabad  2022-05-27     2022  Qualifier 2   
3    1312197      Kolkata  2022-05-24     2022  Qualifier 1   
5    1304115       Mumbai  2022-05-21     2022           69   
8    1304112  Navi Mumbai  2022-05-18     2022           66   
11   1304109       Mumbai  2022-05-15     2022           63   
..       ...          ...         ...      ...          ...   
935   335996    Bangalore  2008-04-28  2007/08           15   
937   335994       Mumbai  2008-04-27  2007/08           14   
939   335992    Bangalore  2008-04-26  2007/08           12   
941   335990    Hyderabad  2008-04-24  2007/08            9   
948   335983   Chandigarh  2008-04-19  2007/08            2   

                           Team1                  Team2  \
1    Royal Challengers Bangalore       Rajasthan Royals   
3               Rajasthan Royals         Gujarat Titans   
5                 Delhi Capitals         Mumbai Indians   
8           Lucknow Super Giants  Kolkata Knight Riders   
11              Rajasthan Royals   Lucknow Super Giants   
..                           ...                    ...   
935  Royal Challengers Bangalore    Chennai Super Kings   
937               Mumbai Indians        Deccan Chargers   
939  Royal Challengers Bangalore       Rajasthan Royals   
941              Deccan Chargers       Rajasthan Royals   
948              Kings XI Punjab    Chennai Super Kings   

                                          Venue            TossWinner  \
1              Narendra Modi Stadium, Ahmedabad      Rajasthan Royals   
3                         Eden Gardens, Kolkata        Gujarat Titans   
5                      Wankhede Stadium, Mumbai        Mumbai Indians   
8            Dr DY Patil Sports Academy, Mumbai  Lucknow Super Giants   
11                    Brabourne Stadium, Mumbai      Rajasthan Royals   
..                                          ...                   ...   
935                       M Chinnaswamy Stadium   Chennai Super Kings   
937                  Dr DY Patil Sports Academy       Deccan Chargers   
939                       M Chinnaswamy Stadium      Rajasthan Royals   
941   Rajiv Gandhi International Stadium, Uppal      Rajasthan Royals   
948  Punjab Cricket Association Stadium, Mohali   Chennai Super Kings   

    TossDecision SuperOver           WinningTeam    WonBy  Margin method  \
1          field         N      Rajasthan Royals  Wickets     7.0    NaN   
3          field         N        Gujarat Titans  Wickets     7.0    NaN   
5          field         N        Mumbai Indians  Wickets     5.0    NaN   
8            bat         N  Lucknow Super Giants     Runs     2.0    NaN   
11           bat         N      Rajasthan Royals     Runs    24.0    NaN   
..           ...       ...                   ...      ...     ...    ...   
935          bat         N   Chennai Super Kings     Runs    13.0    NaN   
937        field         N       Deccan Chargers  Wickets    10.0    NaN   
939        field         N      Rajasthan Royals  Wickets     7.0    NaN   
941        field         N      Rajasthan Royals  Wickets     3.0    NaN   
948          bat         N   Chennai Super Kings     Runs    33.0    NaN   

    Player_of_Match                                       Team1Players  \
1        JC Buttler  ['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...   
3         DA Miller  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...   
5         JJ Bumrah  ['PP Shaw', 'DA Warner', 'MR Marsh', 'RR Pant'...   
8         Q de Kock  ['Q de Kock', 'KL Rahul', 'E Lewis', 'DJ Hooda...   
11         TA Boult  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...   
..              ...                                                ...   
935        MS Dhoni  ['B Chipli', 'W Jaffer', 'LRPL Taylor', 'JH Ka...   
937    AC Gilchrist  ['L Ronchi', 'ST Jayasuriya', 'AM Rahane', 'RV...   
939       SR Watson  ['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...   
941       YK P

To get the number

In [ ]:
ipl[ipl['TossWinner']==ipl['WinningTeam']].shape[0]

489

Total number of ipl matches was

In [ ]:
ipl.shape[0]

950

So toss winner is a winning team percentage

In [ ]:
(ipl[ipl['TossWinner']==ipl['WinningTeam']].shape[0]/ipl.shape[0])*100

51.473684210526315

### Question 5: Movies with rating heigher than 8 and vote more than 10000

In [ ]:
movies.head(2)

title_x    imdb_id  \
0  Uri: The Surgical Strike  tt8291224   
1             Battalion 609  tt9472208   

                                         poster_path  \
0  https://upload.wikimedia.org/wikipedia/en/thum...   
1                                                NaN   

                                           wiki_link  \
0  https://en.wikipedia.org/wiki/Uri:_The_Surgica...   
1        https://en.wikipedia.org/wiki/Battalion_609   

                    title_y            original_title  is_adult  \
0  Uri: The Surgical Strike  Uri: The Surgical Strike         0   
1             Battalion 609             Battalion 609         0   

   year_of_release runtime            genres  imdb_rating  imdb_votes  \
0             2019     138  Action|Drama|War          8.4       35112   
1             2019     131               War          4.1          73   

                                               story  \
0  Divided over five chapters  the film chronicle...   
1  The story revolves around a cricket match betw...   

                                             summary tagline  \
0  Indian army special forces execute a covert op...     NaN   
1  The story of Battalion 609 revolves around a c...     NaN   

                                              actors wins_nominations  \
0  Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...           4 wins   
1  Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...              NaN   

              release_date  
0    11 January 2019 (USA)  
1  11 January 2019 (India)

In [ ]:
movies[(movies['imdb_rating']>8) &(movies['imdb_votes']>10000)].shape[0]

43

### Question 5: Action movies with rating higher than 7.5

In [ ]:
movies.head(2)

title_x    imdb_id  \
0  Uri: The Surgical Strike  tt8291224   
1             Battalion 609  tt9472208   

                                         poster_path  \
0  https://upload.wikimedia.org/wikipedia/en/thum...   
1                                                NaN   

                                           wiki_link  \
0  https://en.wikipedia.org/wiki/Uri:_The_Surgica...   
1        https://en.wikipedia.org/wiki/Battalion_609   

                    title_y            original_title  is_adult  \
0  Uri: The Surgical Strike  Uri: The Surgical Strike         0   
1             Battalion 609             Battalion 609         0   

   year_of_release runtime            genres  imdb_rating  imdb_votes  \
0             2019     138  Action|Drama|War          8.4       35112   
1             2019     131               War          4.1          73   

                                               story  \
0  Divided over five chapters  the film chronicle...   
1  The story revolves around a cricket match betw...   

                                             summary tagline  \
0  Indian army special forces execute a covert op...     NaN   
1  The story of Battalion 609 revolves around a c...     NaN   

                                              actors wins_nominations  \
0  Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...           4 wins   
1  Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...              NaN   

              release_date  
0    11 January 2019 (USA)  
1  11 January 2019 (India)

Here we can't simply compare the two columns genres and imdb_rating because in ganres there are multiple ganres combined together with 'Action' and others, So first we have to find out the geners that have 'Action' in it and then compair them with rating.

To do that, we're gonna read the series as a string, this is gonna give us the whole thing as a string. Then to seperate every genre, we'll use split function to split the whole string based on'|' as this is what seperate the genres. Then we'll apply alogic to chech if 'Action' exits in the series, if does then we'll compare them with the ratings and this will give us the number of action movies that are more than 7.5 ratings

In [ ]:
movies['genres']

0       Action|Drama|War
1                    War
2        Biography|Drama
3            Crime|Drama
4                  Drama
              ...       
1624               Drama
1625               Drama
1626        Comedy|Drama
1627              Action
1628       Drama|Romance
Name: genres, Length: 1629, dtype: object

In [ ]:
movies['genres'].str

In [ ]:
movies['genres'].str.split('|')

0       [Action, Drama, War]
1                      [War]
2         [Biography, Drama]
3             [Crime, Drama]
4                    [Drama]
                ...         
1624                 [Drama]
1625                 [Drama]
1626         [Comedy, Drama]
1627                [Action]
1628        [Drama, Romance]
Name: genres, Length: 1629, dtype: object

In [ ]:
movies['genres'].str.split('|').apply(lambda x: 'Action' in x)

0        True
1       False
2       False
3       False
4       False
        ...  
1624    False
1625    False
1626    False
1627     True
1628    False
Name: genres, Length: 1629, dtype: bool

In [ ]:
movies[(movies['genres'].str.split('|').apply(lambda x: 'Action' in x)) & (movies['imdb_rating']==7.5)].shape[0]
#movies[(movies['genres'].str.contains('Action')) & (movies['imdb_rating']==7.5)].shape[0] # without using apply

4

### Question 6: write a function that can return the track record of 2 teams against each other --task

In [ ]:
ipl.head(2)

ID       City        Date Season  MatchNumber  \
0  1312200  Ahmedabad  2022-05-29   2022        Final   
1  1312199  Ahmedabad  2022-05-27   2022  Qualifier 2   

                         Team1             Team2  \
0             Rajasthan Royals    Gujarat Titans   
1  Royal Challengers Bangalore  Rajasthan Royals   

                              Venue        TossWinner TossDecision SuperOver  \
0  Narendra Modi Stadium, Ahmedabad  Rajasthan Royals          bat         N   
1  Narendra Modi Stadium, Ahmedabad  Rajasthan Royals        field         N   

        WinningTeam    WonBy  Margin method Player_of_Match  \
0    Gujarat Titans  Wickets     7.0    NaN       HH Pandya   
1  Rajasthan Royals  Wickets     7.0    NaN      JC Buttler   

                                        Team1Players  \
0  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...   
1  ['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...   

                                        Team2Players      Umpire1      Umpire2  
0  ['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...  CB Gaffaney  Nitin Menon  
1  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...  CB Gaffaney  Nitin Menon

In [ ]:
team1 = ipl[ipl['WinningTeam']== 'Gujarat Titans'].shape[0]
team1

12

In [ ]:
team2 = ipl[ipl['WinningTeam']== 'Rajasthan Royals'].shape[0]
team2

96

In [ ]:
def track(team1,team2):
    t1 = ipl[ipl['WinningTeam']== team1].shape[0]
    t2 = ipl[ipl['WinningTeam']== team2].shape[0]
    return team1,':',t1,'   ',team2,':',t2
te1 = input("Enter Team 1: ")
te2 = input("Enter Team 2: ")

track(te1,te2)


('Gujarat Titans', ':', 12, '   ', 'Rajasthan Royals', ':', 96)

# Adding new column

### Add a new coulmn

To add a new column we can just use dataframe name and pass the name of the column inside a square bracket and give it a name, for example to add a new column like country we can write movies['Country'] = 'Country_name'

In [ ]:
movies['Country'] = 'India'

In [ ]:
movies.head(2)

title_x    imdb_id  \
0  Uri: The Surgical Strike  tt8291224   
1             Battalion 609  tt9472208   

                                         poster_path  \
0  https://upload.wikimedia.org/wikipedia/en/thum...   
1                                                NaN   

                                           wiki_link  \
0  https://en.wikipedia.org/wiki/Uri:_The_Surgica...   
1        https://en.wikipedia.org/wiki/Battalion_609   

                    title_y            original_title  is_adult  \
0  Uri: The Surgical Strike  Uri: The Surgical Strike         0   
1             Battalion 609             Battalion 609         0   

   year_of_release runtime            genres  imdb_rating  imdb_votes  \
0             2019     138  Action|Drama|War          8.4       35112   
1             2019     131               War          4.1          73   

                                               story  \
0  Divided over five chapters  the film chronicle...   
1  The story revolves around a cricket match betw...   

                                             summary tagline  \
0  Indian army special forces execute a covert op...     NaN   
1  The story of Battalion 609 revolves around a c...     NaN   

                                              actors wins_nominations  \
0  Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...           4 wins   
1  Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...              NaN   

              release_date Country  
0    11 January 2019 (USA)   India  
1  11 January 2019 (India)   India

### Add a column from a exiting column

Let's add a new column called 'Lead actor' and the value of the column will be the first name of the actors column

Let's take a look at the acrots name, the code below return a series of actors

In [ ]:
movies['actors']

0       Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...
1       Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...
2       Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...
3       Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...
4       Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...
                              ...                        
1624    Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...
1625    Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...
1626    Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...
1627                            Gippy Grewal|Zareen Khan|
1628                                          Fawad Khan|
Name: actors, Length: 1629, dtype: object

As this is a series we'll take the string format of the series and split them on the basis of '|', this would return a series of list of the actors names

In [ ]:
movies['actors'].str.split('|')

0       [Vicky Kaushal, Paresh Rawal, Mohit Raina, Yam...
1       [Vicky Ahuja, Shoaib Ibrahim, Shrikant Kamat, ...
2       [Anupam Kher, Akshaye Khanna, Aahana Kumra, At...
3       [Emraan Hashmi, Shreya Dhanwanthary, Snighdade...
4       [Mona Ambegaonkar, Ananth Narayan Mahadevan, D...
                              ...                        
1624    [Ajay Devgn, Sonali Bendre, Namrata Shirodkar,...
1625    [Ameesha Patel, Jimmy Sheirgill, Nafisa Ali, G...
1626    [Vijay Arora, Asrani, Rajni Bala, Kumud Damle,...
1627                        [Gippy Grewal, Zareen Khan, ]
1628                                       [Fawad Khan, ]
Name: actors, Length: 1629, dtype: object

If we try to fletch the first item of the series, it wouldn't work as it's gonna only return the first list of the series, that contains all the names of the actors

In [ ]:
movies['actors'].str.split('|')[0]

['Vicky Kaushal',
 'Paresh Rawal',
 'Mohit Raina',
 'Yami Gautam',
 'Kirti Kulhari',
 'Rajit Kapoor',
 'Ivan Rodrigues',
 'Manasi Parekh',
 'Swaroop Sampat',
 'Riva Arora',
 'Yogesh Soman',
 'Fareed Ahmed',
 'Akashdeep Arora',
 'Kallol Banerjee',
 '']

So we'll apply a logic to extract the first element of all the values of the column 'actors'

In [ ]:
movies['actors'].str.split('|').apply(lambda x: x[0])

TypeError: 'float' object is not subscriptable

The error we got because of the missing values, so first take care of the missing values eusing dropna() then apply the logic

In [ ]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1629 entries, 0 to 1628
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   title_x           1629 non-null   object 
 1   imdb_id           1629 non-null   object 
 2   poster_path       1526 non-null   object 
 3   wiki_link         1629 non-null   object 
 4   title_y           1629 non-null   object 
 5   original_title    1629 non-null   object 
 6   is_adult          1629 non-null   int64  
 7   year_of_release   1629 non-null   int64  
 8   runtime           1629 non-null   object 
 9   genres            1629 non-null   object 
 10  imdb_rating       1629 non-null   float64
 11  imdb_votes        1629 non-null   int64  
 12  story             1609 non-null   object 
 13  summary           1629 non-null   object 
 14  tagline           557 non-null    object 
 15  actors            1624 non-null   object 
 16  wins_nominations  707 non-null    object 


If we look at the RangeIndex the actors Non-Null values is 1624, the highest Non-null value is 1629 so 5 missing values.

Let's take care of them

In [ ]:
movies['actors'].dropna()

0       Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...
1       Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...
2       Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...
3       Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...
4       Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...
                              ...                        
1624    Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...
1625    Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...
1626    Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...
1627                            Gippy Grewal|Zareen Khan|
1628                                          Fawad Khan|
Name: actors, Length: 1624, dtype: object

Now apply the same logic again, we are able to seperate the first actor name from the actors column

In [ ]:
movies['actors'].dropna().str.split('|').apply(lambda x:x[0])

0          Vicky Kaushal
1            Vicky Ahuja
2            Anupam Kher
3          Emraan Hashmi
4       Mona Ambegaonkar
              ...       
1624          Ajay Devgn
1625       Ameesha Patel
1626         Vijay Arora
1627        Gippy Grewal
1628          Fawad Khan
Name: actors, Length: 1624, dtype: object

Now add this sereis in a new column

In [ ]:
movies['Lead actor'] = movies['actors'].dropna().str.split('|').apply(lambda x:x[0])

Now if we check we can see the new column has been added

In [ ]:
movies.head()

title_x    imdb_id  \
0              Uri: The Surgical Strike  tt8291224   
1                         Battalion 609  tt9472208   
2  The Accidental Prime Minister (film)  tt6986710   
3                       Why Cheat India  tt8108208   
4                       Evening Shadows  tt6028796   

                                         poster_path  \
0  https://upload.wikimedia.org/wikipedia/en/thum...   
1                                                NaN   
2  https://upload.wikimedia.org/wikipedia/en/thum...   
3  https://upload.wikimedia.org/wikipedia/en/thum...   
4                                                NaN   

                                           wiki_link  \
0  https://en.wikipedia.org/wiki/Uri:_The_Surgica...   
1        https://en.wikipedia.org/wiki/Battalion_609   
2  https://en.wikipedia.org/wiki/The_Accidental_P...   
3      https://en.wikipedia.org/wiki/Why_Cheat_India   
4      https://en.wikipedia.org/wiki/Evening_Shadows   

                         title_y                 original_title  is_adult  \
0       Uri: The Surgical Strike       Uri: The Surgical Strike         0   
1                  Battalion 609                  Battalion 609         0   
2  The Accidental Prime Minister  The Accidental Prime Minister         0   
3                Why Cheat India                Why Cheat India         0   
4                Evening Shadows                Evening Shadows         0   

   year_of_release runtime            genres  imdb_rating  imdb_votes  \
0             2019     138  Action|Drama|War          8.4       35112   
1             2019     131               War          4.1          73   
2             2019     112   Biography|Drama          6.1        5549   
3             2019     121       Crime|Drama          6.0        1891   
4             2018     102             Drama          7.3         280   

                                               story  \
0  Divided over five chapters  the film chronicle...   
1  The story revolves around a cricket match betw...   
2  Based on the memoir by Indian policy analyst S...   
3  The movie focuses on existing malpractices in ...   
4  While gay rights and marriage equality has bee...   

                                             summary tagline  \
0  Indian army special forces execute a covert op...     NaN   
1  The story of Battalion 609 revolves around a c...     NaN   
2  Explores Manmohan Singh's tenure as the Prime ...     NaN   
3  The movie focuses on existing malpractices in ...     NaN   
4  Under the 'Evening Shadows'  truth often plays...     NaN   

                                              actors        wins_nominations  \
0  Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...                  4 wins   
1  Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...                     NaN   
2  Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...                     NaN   
3  Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...                     NaN   
4  Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...  17 wins & 1 nomination   

              release_date Country        Lead actor  
0    11 January 2019 (USA)   India     Vicky Kaushal  
1  11 January 2019 (India)   India       Vicky Ahuja  
2    11 January 2019 (USA)   India       Anupam Kher  
3    18 January 2019 (USA)   India     Emraan Hashmi  
4  11 January 2019 (India)   India  Mona Ambegaonkar

If we check the shape it's 1629 that means the rows that had missing values those rows are still empty in the new column 

In [ ]:
movies.shape

(1629, 20)

# Important DataFrame Functions

### astype()

Use to change a data type

In [ ]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1629 entries, 0 to 1628
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   title_x           1629 non-null   object 
 1   imdb_id           1629 non-null   object 
 2   poster_path       1526 non-null   object 
 3   wiki_link         1629 non-null   object 
 4   title_y           1629 non-null   object 
 5   original_title    1629 non-null   object 
 6   is_adult          1629 non-null   int64  
 7   year_of_release   1629 non-null   int64  
 8   runtime           1629 non-null   object 
 9   genres            1629 non-null   object 
 10  imdb_rating       1629 non-null   float64
 11  imdb_votes        1629 non-null   int64  
 12  story             1609 non-null   object 
 13  summary           1629 non-null   object 
 14  tagline           557 non-null    object 
 15  actors            1624 non-null   object 
 16  wins_nominations  707 non-null    object 


So if we look at the basic information some of the datatype are int64 which is use to store very large number of integer value, we don't need that because if we check for all the cases the maximum value is not that big, so keep their data type as int64 is waste of memory, so here we can assign a data type that consume less memory to same the memory consumption by the dataset. Write now the memory usage is about 255kb 

In [ ]:
movies['is_adult'].max()

0

In [ ]:
movies['year_of_release'].max()

2019

In [ ]:
movies['imdb_votes'].max()

310481

So let's assign them a datatype that takes less memory by using astype()

In [ ]:
movies['is_adult'].astype('Int16')

0       0
1       0
2       0
3       0
4       0
       ..
1624    0
1625    0
1626    0
1627    0
1628    0
Name: is_adult, Length: 1629, dtype: Int16

To make the permanent change

In [ ]:
movies['is_adult'] = movies['is_adult'].astype('Int16')

Now let's do the same thing for the others

In [ ]:
movies['year_of_release'] = movies['year_of_release'].astype('Int16')
movies['imdb_votes'] = movies['imdb_votes'].astype('Int32')

Now if we see the memory consumption

In [ ]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1629 entries, 0 to 1628
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   title_x           1629 non-null   object 
 1   imdb_id           1629 non-null   object 
 2   poster_path       1526 non-null   object 
 3   wiki_link         1629 non-null   object 
 4   title_y           1629 non-null   object 
 5   original_title    1629 non-null   object 
 6   is_adult          1629 non-null   Int16  
 7   year_of_release   1629 non-null   Int16  
 8   runtime           1629 non-null   object 
 9   genres            1629 non-null   object 
 10  imdb_rating       1629 non-null   float64
 11  imdb_votes        1629 non-null   Int32  
 12  story             1609 non-null   object 
 13  summary           1629 non-null   object 
 14  tagline           557 non-null    object 
 15  actors            1624 non-null   object 
 16  wins_nominations  707 non-null    object 


In [ ]:
ipl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   ID               950 non-null    int64  
 1   City             899 non-null    object 
 2   Date             950 non-null    object 
 3   Season           950 non-null    object 
 4   MatchNumber      950 non-null    object 
 5   Team1            950 non-null    object 
 6   Team2            950 non-null    object 
 7   Venue            950 non-null    object 
 8   TossWinner       950 non-null    object 
 9   TossDecision     950 non-null    object 
 10  SuperOver        946 non-null    object 
 11  WinningTeam      946 non-null    object 
 12  WonBy            950 non-null    object 
 13  Margin           932 non-null    float64
 14  method           19 non-null     object 
 15  Player_of_Match  946 non-null    object 
 16  Team1Players     950 non-null    object 
 17  Team2Players    

In [ ]:
ipl['ID'].max()

1312200

In [ ]:
ipl['ID'] = ipl['ID'].astype('Int32')

Similarly the columns 'team1','team2','Season' have repeated string values so we can change their datatype to 'category'

In [ ]:
ipl['Season'] = ipl['Season'].astype('category')
ipl['Team1'] = ipl['Team1'].astype('category')
ipl['Team2'] = ipl['Team2'].astype('category')
ipl['TossWinner'] = ipl['TossWinner'].astype('category')

In [ ]:
ipl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype   
---  ------           --------------  -----   
 0   ID               950 non-null    Int32   
 1   City             899 non-null    object  
 2   Date             950 non-null    object  
 3   Season           950 non-null    category
 4   MatchNumber      950 non-null    object  
 5   Team1            950 non-null    category
 6   Team2            950 non-null    category
 7   Venue            950 non-null    object  
 8   TossWinner       950 non-null    category
 9   TossDecision     950 non-null    object  
 10  SuperOver        946 non-null    object  
 11  WinningTeam      946 non-null    object  
 12  WonBy            950 non-null    object  
 13  Margin           932 non-null    float64 
 14  method           19 non-null     object  
 15  Player_of_Match  946 non-null    object  
 16  Team1Players     950 non-null    object  
 1